package com.vertex.quality.connectors.magento.common.enums;

import lombok.Getter;

/**
 * Data for Magento
 *
 * @author alewis
 */
@Getter
public enum MagentoData
{
	MEDIA_ADDRESS("99 Park Ave"),
	WESTCHESTER_ADDRESS("400 Sharpless Street"),
	WC_ADDRESS_OPTION("John Winston, 2 West Gay Street, West Chester, Pennsylvania 19380, United States"),
	MEDIA_ZIPCODE("19063"),
	WESTCHESTER_ZIPCODE("19382"),
	MD_ZIPCODE("21204"),
	PA_TAX_PERCENT("6%"),
	IL_TAX_PERCENT("6.25%"),
	CANADA_TAX_PERCENT("15%"),
	CANADA_TAX_PERCENT2("15%"),
	PA_TAX_NUMBER("0.06"),
	PA_TAX_NUMBER2("0.07"),
	PA_TAX_NUMBER_2("0.003"),
	CANADA_TAX_NUMBER("0.15"),
	CA_TAX_NUMBER("0.103"),
	IL_TAX_NUMBER("0.0625"),
	Exemption_RATE("1.028"),
	Exemption_Rate_SUBTOTAL("1.026"),
	Exemption_SALESUSE_RATE("0.026"),
	PA_TAX_RATE("1.06"),
	PA_TAX_RATE_2("1"),
	CANADA_TAX_RATE("1.15"),
	CANADA_TAX_RATE_2("0.56"),
	CA_TAX_RATE_3("1.103"),
	CA_TAX_RATE("1.1025"),
	CA_EXEMPTION_RATE("1.10"),
	NO_TAX_RATE("1.0"),
	IL_TAX_RATE("1.063"),
	LA_TAX_RATE("9.45"),
	WA_TAX_RATE("6.5"),
	EXEMPT_TAX("0.0"),
	JP_TAX_RATE("10.0"),
	PA_NUMBER("51"),
	MAGENTO_PROD_2_0_ADMIN("http://magento2.vertexconnectors.com/admin"),
	MAGENTO_PROD_2_0_STORE("http://magento2.vertexconnectors.com/"),
	MAGENTO_QA_2_0_ADMIN("http://magento2-qa.vertexconnectors.com/admin"),
	MAGENTO_QA_2_0_STORE("http://magento2-qa.vertexconnectors.com/"),
	MAGENTO_DEV_2_0_ADMIN("http://magento2-dev.vertexconnectors.com/admin"),
	MAGENTO_DEV_2_0_STORE("http://magento2-dev.vertexconnectors.com/"),
	ADMIN_SIGN_ON_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/admin"),
	STOREFRONT_SIGN_ON_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/"),
	STOREFRONT_VIRTUAL_PRODUCT_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/aaron-s-virtual.html"),
	STOREFRONT_DOWNLOADABLE_PRODUCT_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/solo-power-circuit.html"),
	STOREFRONT_HERO_HOODIE_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/hero-hoodie.html"),
	STOREFRONT_FITNESS_TANK_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/atlas-fitness-tank.html"),
	STOREFRONT_SPCM_URL("https://test-ee-latest.vrtx-m2.mediotype.ninja/spcm.html"),
	STOREFRONT_COMPANION_BUNDLE("https://test-ee-latest.vrtx-m2.mediotype.ninja/sprite-yoga-companion-kit.html"),
	STOREFRONT_PRODUCT_DETAILS("https://test-ee-latest.vrtx-m2.mediotype.ninja/checkout/cart/"),
	STOREFRONT_STRAPS_BUNDLE("https://test-ee-latest.vrtx-m2.mediotype.ninja/set-of-sprite-yoga-straps.html"),
	TRUSTED_ID("1405705348746247"),
	CALCULATION_API_URL("https://mgcsconnect.vertexsmb.com/vertex-ws/services/CalculateTax70"),
	ADDRESS_VALIDATION_API_URL("https://mgcsconnect.vertexsmb.com/vertex-ws/services/LookupTaxAreas70"),
	CALCULATION_INVALID_URL("https://mgcsconnect.vertexsmb.com/vertex-ws/services/CalculateTax00"),
	ADDRESS_VALIDATION_INVALID_URL("https://mgcsconnect.vertexsmb.com/vertex-ws/services/LookupTaxAreas00"),
	MAGENTO_2_0_ADMIN_USER("admin"),
	MAGENTO_2_0_AUTOMATION_USER_ADMIN_PANEL("automation"),
	MAGENTO_2_0_ADMIN_PASSWORD("admin123@"),
	MAGENTO_2_0_STORE_USER("test_magento@xyz.com"),
	MAGENTO_2_0_STORE_PASSWORD("test123@"),
	MAGENTO_2_0_CUSTOMER_CODE("customer.code@test.com"),
	MAGENTO_2_0_CUSTOMER_CLASS("customer.class@test.com"),
	MAGENTO_2_0_CUSTOMER_CODE_CLASS_PW("Test@123"),
	ADMIN_USERNAME("admin"),
	ADMIN_PASSWORD("Mag3nt0*"),
	STOREFRONT_USERNAME("akl524psu@gmail.com"),
	JOHN_WINSTON_USERNAME("asfdjwer@sdfasd.com"),
	STOREFRONT_PASSWORD("Vertex2018"),
	MD_STOREFRONT_USERNAME("alewis@vertexinc.com"),
	ARDERN_STOREFRONT_USERNAME("jacinda.ardern@gmail.com"),
	CATRINA_ARAGON("vlouisedCatrina@aol.com"),
	CATE_DEMEDICI("vlouisedCate@aol.com"),
	GOLDBLUM_USERNAME("akl5248@psu.edu"),

	oneHundredDollars("$100.00"),
	oneHundredSixDollars("$106.00"),
	oneHundredSeventySix_ThirtyTwo_Dollars("$176.32"),
	oneHundredSeventyTwoDollars("$172.00"),
	twoHundredDollars("$200.00"),
	twoHundredTwelveDollars("$212.00"),
	twoHundredTwelveDollars_Fifty_Dollars("$212.50"),
	nineteen_EightDollars("$19.08"),
	eighteenDollars("$18.00"),
	five_twentyTwoDollars("$5.22"),
	four_thirtyTwoDollars("$4.32"),
	twoHundredTwelve("212.0"),
	twoHundred("200.0"),
	oneHundredEightySeven("187.0"),
	oneHundredNinetyTwo_TwentyTwo("192.22"),
	oneHundredSeventyTwo("172.0"),
	oneHundredSeventySix_ThirtyTwo("176.32"),
	oneHundred("100.0"),
	FiftySevenTwentyFourDollars("$57.24"),
	FiftyFourDollars("$54.00"),
	twelveDollars("$12.00"),
	twelve("12.0"),
	four_thirtyTwo("4.32"),
	discount_percentage("19.75"),
	fixedDiscount_percentage("5.0"),
	tenDollar_Discount("10.0"),
	shipping_discount("5.0"),
	quantity_zero("0"),
	quantity_one("1"),
	quantity_two("2"),
	quantity_three("3"),
	quantity_four("4"),
	quantity_five("5"),
	quantity_ten("10"),
	quantity_twelve("12"),

	EU_TAX_RATE("0.2"),
	EU_BILLING_FIRST_NAME("tom"),
	EU_BILLING_LAST_NAME("cruise"),
	EU_BILLING_STREET0("1270 York Road"),
	EU_BILLING_COUNTRY("United States"),
	EU_BILLING_STATE("Pennsylvania"),
	EU_BILLING_CITY("Gettysburg"),
	EU_BILLING_ZIP("17325"),
	EU_BILLING_PHONE("4848685708"),
	EU_SHIPPING_FIRST_NAME("jemmy"),
	EU_SHIPPING_LAST_NAME("watson"),
	EU_SHIPPING_STREET0("Port de la Bourdonnais"),
	EU_SHIPPING_COUNTRY("France"),
	EU_SHIPPING_STATE("Paris"),
	EU_SHIPPING_CITY("Paris"),
	EU_SHIPPING_ZIP("75007"),
	EU_SHIPPING_PHONE("4848685708"),

	FR_BILLING_FIRST_NAME("jemmy"),
	FR_BILLING_LAST_NAME("watson"),
	FR_BILLING_STREET0("Port de la Bourdonnais"),
	FR_BILLING_COUNTRY("France"),
	FR_BILLING_STATE("Paris"),
	FR_BILLING_CITY("Paris"),
	FR_BILLING_ZIP("75007"),
	FR_BILLING_PHONE("4848685708"),

	AT_TAX_RATE("0.0"),
	AT_BILLING_FIRST_NAME("Tom"),
	AT_BILLING_LAST_NAME("Tr"),
	AT_BILLING_STREET0("Allée du Stade"),
	AT_BILLING_COUNTRY("Germany"),
	AT_BILLING_STATE("Berlin"),
	AT_BILLING_CITY("Berlin"),
	AT_BILLING_ZIP("13405"),
	AT_BILLING_PHONE("4848685709"),
	AT_SHIPPING_FIRST_NAME("John"),
	AT_SHIPPING_LAST_NAME("Jr"),
	AT_SHIPPING_STREET0("Moosstr. 7"),
	AT_SHIPPING_COUNTRY("Austria"),
	AT_SHIPPING_STATE("Vorarlberg"),
	AT_SHIPPING_CITY("Mittelberg"),
	AT_SHIPPING_ZIP("6993"),
	AT_SHIPPING_PHONE("4848685709"),
	AT_SHIPPING2_FIRST_NAME("Tom"),
	AT_SHIPPING2_LAST_NAME("Tr"),
	AT_SHIPPING2_STREET0("Allée du Stade"),
	AT_SHIPPING2_COUNTRY("Germany"),
	AT_SHIPPING2_STATE("Brandenburg"),
	AT_SHIPPING2_CITY("Berlin"),
	AT_SHIPPING2_ZIP("13405"),
	AT_SHIPPING2_PHONE("4848685709"),

	SG_BILLING_FIRST_NAME("Tom"),
	SG_BILLING_LAST_NAME("Tr"),
	SG_BILLING_STREET0("510 Upper Jurong Road"),
	SG_BILLING_COUNTRY("Singapore"),
	SG_BILLING_STATE("Singapore"),
	SG_BILLING_CITY("Jurong"),
	SG_BILLING_ZIP("638365"),
	SG_BILLING_PHONE("4848685709"),

	JP_SHIPPING_FIRST_NAME("Tom"),
	JP_SHIPPING_LAST_NAME("Tr"),
	JP_SHIPPING_STREET0("Ginza 5-5-6"),
	JP_SHIPPING_COUNTRY("Japan"),
	JP_SHIPPING_STATE("Tōkyō-to"),
	JP_SHIPPING_CITY("Chuo-ku"),
	JP_SHIPPING_ZIP("104-0061"),
	JP_SHIPPING_PHONE("4848685709"),

	US_SHIPPING_FIRST_NAME("John"),
	US_SHIPPING_LAST_NAME("Jr"),
	US_SHIPPING_STREET0("100 Universal City Plazza"),
	US_SHIPPING_COUNTRY("United States"),
	US_SHIPPING_STATE("California"),
	US_SHIPPING_CITY("University"),
	US_SHIPPING_INVALID_CITY("Chester"),
	US_SHIPPING_ZIP("91608-1002"),
	US_SHIPPING_INVALID_ZIP("99999"),
	US_SHIPPING_PHONE("4848685709"),
	US_BILLING_FIRST_NAME("John"),
	US_BILLING_LAST_NAME("Jr"),
	US_BILLING_STREET0("100 Universal City Plazza"),
	US_BILLING_COUNTRY("United States"),
	US_BILLING_STATE("California"),
	US_BILLING_CITY("University"),
	US_BILLING_INVALID_CITY("Chester"),
	US_BILLING_ZIP("91608-1002"),
	US_BILLING_INVALID_ZIP("99999"),
	US_BILLING_PHONE("4848685709"),

	US_SHIPPING2_FIRST_NAME("John"),
	US_SHIPPING2_LAST_NAME("Jr"),
	US_SHIPPING2_STREET0("1041 Old Cassatt Rd"),
	US_SHIPPING2_COUNTRY("United States"),
	US_SHIPPING2_STATE("Pennsylvania"),
	US_SHIPPING2_CITY("Berwyn"),
	US_SHIPPING2_ZIP("19312"),
	US_SHIPPING2_PHONE("4848685709"),

	US_SHIPPING3_FIRST_NAME("John"),
	US_SHIPPING3_LAST_NAME("Jr"),
	US_SHIPPING3_STREET0("5950 Broadway"),
	US_SHIPPING3_COUNTRY("United States"),
	US_SHIPPING3_STATE("California"),
	US_SHIPPING3_CITY("Los Angeles"),
	US_SHIPPING3_ZIP("90030"),
	US_SHIPPING3_PHONE("4848685709"),
	US_SHIPPING3_TAX_RATE("1.25"),

	US_SHIPPING4_FIRST_NAME("John"),
	US_SHIPPING4_LAST_NAME("Jr"),
	US_SHIPPING4_STREET0("5300 St Charles Ave"),
	US_SHIPPING4_COUNTRY("United States"),
	US_SHIPPING4_STATE("Louisiana"),
	US_SHIPPING4_CITY("New Orleans"),
	US_SHIPPING4_ZIP("70118"),
	US_SHIPPING4_PHONE("4848685709"),

	US_SHIPPING5_FIRST_NAME("John"),
	US_SHIPPING5_LAST_NAME("Jr"),
	US_SHIPPING5_STREET0("1575 Space Center Drive"),
	US_SHIPPING5_COUNTRY("United States"),
	US_SHIPPING5_STATE("Colorado"),
	US_SHIPPING5_CITY("Colorado Springs"),
	US_SHIPPING5_ZIP("80915"),
	US_SHIPPING5_PHONE("4848685709"),

	US_SHIPPING6_FIRST_NAME("John"),
	US_SHIPPING6_LAST_NAME("Jr"),
	US_SHIPPING6_STREET0("NE 8th St22833"),
	US_SHIPPING6_COUNTRY("United States"),
	US_SHIPPING6_STATE("Washington"),
	US_SHIPPING6_CITY("Sammamish"),
	US_SHIPPING6_ZIP("98074"),
	US_SHIPPING6_PHONE("4848685709"),

	WI_SHIPPING_FIRST_NAME("John"),
	WI_SHIPPING_LAST_NAME("Jr"),
	WI_SHIPPING_STREET0("1440 Monroe Street"),
	WI_SHIPPING_COUNTRY("United States"),
	WI_SHIPPING_STATE("Wisconsin"),
	WI_SHIPPING_CITY("Madison"),
	WI_SHIPPING_ZIP("53711"),
	WI_SHIPPING_PHONE("4848685709"),

	GR_TAX_RATE("0.24"),
	GR_SHIPPING_FIRST_NAME("John"),
	GR_SHIPPING_LAST_NAME("Jr"),
	GR_SHIPPING_STREET0("Paralia Schoinonta"),
	GR_SHIPPING_COUNTRY("Greece"),
	GR_SHIPPING_STATE("Thessalía"),
	GR_SHIPPING_CITY("Analipsi"),
	GR_SHIPPING_ZIP("859 00"),
	GR_SHIPPING_PHONE("4848685709"),

	FR_TAX_RATE("0.19"),
	FR_SHIPPING_FIRST_NAME("John"),
	FR_SHIPPING_LAST_NAME("Jr"),
	FR_SHIPPING_STREET0("38-40 Quai De Rive Neuve"),
	FR_SHIPPING_COUNTRY("France"),
	FR_SHIPPING_STATE("Please select"),
	FR_SHIPPING_CITY("Marseille"),
	FR_SHIPPING_ZIP("13007"),
	FR_SHIPPING_PHONE("4848685709"),

	BE_SHIPPING_FIRST_NAME("Sam"),
	BE_SHIPPING_LAST_NAME("Sr"),
	BE_SHIPPING_STREET0("Rue Léopold 2"),
	BE_SHIPPING_COUNTRY("Belgium"),
	BE_SHIPPING_STATE("Please select"),
	BE_SHIPPING_CITY("La Louvière"),
	BE_SHIPPING_ZIP("7100"),
	BE_SHIPPING_PHONE("4848685709"),

	PR_TAX_RATE("0.1"),
	PR_SHIPPING_FIRST_NAME("Sam"),
	PR_SHIPPING_LAST_NAME("Sr"),
	PR_SHIPPING_STREET0("30 Calle Mayor Cantera"),
	PR_SHIPPING_COUNTRY("United States"),
	PR_SHIPPING_STATE("Puerto Rico"),
	PR_SHIPPING_CITY("Ponce"),
	PR_SHIPPING_ZIP("00730-3023"),
	PR_SHIPPING_PHONE("4848685709"),

	DE_TAX_RATE("0.19"),
	DE_SHIPPING_FIRST_NAME("Sam"),
	DE_SHIPPING_LAST_NAME("Sr"),
	DE_SHIPPING_STREET0("Oranienstraße 138"),
	DE_SHIPPING_COUNTRY("Germany"),
	DE_SHIPPING_STATE("Brandenburg"),
	DE_SHIPPING_CITY("Berlin"),
	DE_SHIPPING_ZIP("10969"),
	DE_SHIPPING_PHONE("4848685709"),

	ADDRESS_CORRECTION_MSG("The address could not be validated. Please ensure it is correct before continuing."),
	ADDRESS_SUGGESTION_MSG("The intended address could be:"),
	ADDRESS_WARNING_MSG("Warning: Updating the address will replace all street address fields."),

	TEN_DOLLAR_ORDER("10DollarOrder"),
	TEN_DOLLAR_ITEM("10DollarItem"),
	TEN_PERCENT_ORDER("10PercentOrder"),
	ONE_OFF_SHIP("1OFFShip"),
	FIVE_PERCENT_ORDER("5PercentOrder"),
	FIVE_PERCENT_ITEM("5PercentItem"),
	FIVE_DOLLAR_ORDER("5DollarOrder"),

	SHIP_TERM_CUS("CUS - Customer Ships"),
	SHIP_TERM_SUP("SUP - Supplier Ships"),
	SHIP_TERM_DDP("DDP - Delivery Duty Paid"),
	SHIP_TERM_EXW("EXW - Ex Works"),

	PARTIAL_RETURN_AMOUNT("25"),
	FULL_RETURN_AMOUNT("0"),
	LOGGED_IN("loggedIn"),
	LOGGED_OUT("loggedOut"),

	VERTEX_API_VALID("VALID"),
	VERTEX_CACL_API_INVALID("UNABLE TO CONNECT TO CALCULATION API"),
	VERTEX_ADD_API_INVALID("UNABLE TO CONNECT TO ADDRESS VALIDATION API"),
	VERTEX_URL_CALC("CALCULATION"),
	VERTEX_URL_ADDRESS("ADDRESS_VALIDATION"),

	CUSTOMER_FIRST_NAME("rohit"),
	CUSTOMER_LAST_NAME("test"),
	CUSTOMER_CODE_CUSTOMER_NAME("Customer Code"),
	CUSTOMER_CLASS_CUSTOMER_NAME("Customer Class"),
	CUSTOMER_CLASS("VTXCClass"),
	GENERAL_CUSTOMER_CLASS("General"),
	CUSTOMER_CODE("VTXCCode1"),

	ADMIN_PRODUCT_1("MH12-XS-Blue"),
	ADMIN_PRODUCT_2("WSH12-32-Red"),
	ADMIN_PRODUCT_3("WSH11-29-Red"),
	ADMIN_PRODUCT_4("WSH10-29-White"),
	FUSION_BACKPACK("Fusion Backpack"),
	PUSH_IT_MESSENGER_BAG("Push It Messenger Bag"),
	QA_ROUND_OFF_PRODUCT("qa-round-off-price-product"),
	QA_EXEMPTED_VIRTUAL_PRODUCT("qa-exempted-virtual-product"),
	QA_EXEMPTED_PHYSICAL_PRODUCT("qa-exempted-physical-product"),
	QA_COMMODITY_CODE_PRODUCT("qa-commodity-product"),

	ADMIN_NODE_ORIGIN("Origin"),

	COLORADO_RETAIL_DELIVERY_FEE(0.27),
	TAX_COLORADO_RETAIL_DELIVERY(5.4),

	innerHTML("innerHTML");

	public String data;
	public double value;

	MagentoData( String data )
	{
		this.data = data;
	}
	MagentoData( double value ) { this.value = value; }
}