CREATE DATABASE [Ariba1_QA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ariba1_QA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Ariba1_QA.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ariba1_QA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Ariba1_QA_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
ALTER DATABASE [Ariba1_QA] SET COMPATIBILITY_LEVEL = 140
ALTER DATABASE [Ariba1_QA] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [Ariba1_QA] SET ANSI_NULLS OFF 
ALTER DATABASE [Ariba1_QA] SET ANSI_PADDING OFF 
ALTER DATABASE [Ariba1_QA] SET ANSI_WARNINGS OFF 
ALTER DATABASE [Ariba1_QA] SET ARITHABORT OFF 
ALTER DATABASE [Ariba1_QA] SET AUTO_CLOSE OFF 
ALTER DATABASE [Ariba1_QA] SET AUTO_SHRINK OFF 
ALTER DATABASE [Ariba1_QA] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
ALTER DATABASE [Ariba1_QA] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [Ariba1_QA] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [Ariba1_QA] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [Ariba1_QA] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [Ariba1_QA] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [Ariba1_QA] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [Ariba1_QA] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [Ariba1_QA] SET DISABLE_BROKER 
ALTER DATABASE [Ariba1_QA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [Ariba1_QA] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [Ariba1_QA] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [Ariba1_QA] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [Ariba1_QA] SET READ_WRITE 
ALTER DATABASE [Ariba1_QA] SET RECOVERY FULL 
ALTER DATABASE [Ariba1_QA] SET MULTI_USER 
ALTER DATABASE [Ariba1_QA] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [Ariba1_QA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE [Ariba1_QA] SET DELAYED_DURABILITY = DISABLED 
